### ISSUE TITLE
feat: Parse tx logs for unnecessary quotation symbols and events

### ISSUE THREAD

**Issue by Unique-Divine** [NibiruChain/ts-sdk#68] opened 2022-12-08 21:00 UTC
- [ ] Let's open a ticket to add a more clean way to parse tx logs

_Originally posted by @Unique-Divine in https://github.com/NibiruChain/web-app-nibiru/pull/178#discussion_r1043796045_

We can wrap the POJOs in a class that has convenience functions on top of it.

**Comment by cgilbe27** [comment] 2024-06-12 18:48
Duplicate of https://github.com/NibiruChain/ts-sdk/issues/60

**Closed as completed by cgilbe27** 2024-06-12 18:48 UTC
Labels: type: enhance
